/* ===== 数据版本（自动按日期生成，改了 data.js 后部署即自动刷新） ===== */
var DATA_VERSION = (function(){
  var d = new Date();
  return 'd' + d.getFullYear() + (d.getMonth()+1) + d.getDate() + 'r' + d.getHours();
})();
var SITE_NAME_MAP = {
  '淘宝': 'https://www.taobao.com', '天猫': 'https://www.tmall.com', '京东': 'https://www.jd.com',
  '拼多多': 'https://www.pinduoduo.com', '唯品会': 'https://www.vip.com', '苏宁': 'https://www.suning.com',
  '亚马逊': 'https://www.amazon.cn', '1688': 'https://www.1688.com', '阿里巴巴': 'https://www.alibaba.com',
  '百度': 'https://www.baidu.com', '谷歌': 'https://www.google.com', '必应': 'https://www.bing.com',
  '搜狗': 'https://www.sogou.com', '360': 'https://www.so.com', '知乎': 'https://www.zhihu.com',
  '微博': 'https://weibo.com', '哔哩哔哩': 'https://www.bilibili.com', 'B站': 'https://www.bilibili.com',
  '抖音': 'https://www.douyin.com', '快手': 'https://www.kuaishou.com', '小红书': 'https://www.xiaohongshu.com',
  '豆瓣': 'https://www.douban.com', '贴吧': 'https://tieba.baidu.com', '微信': 'https://weixin.qq.com',
  'QQ': 'https://im.qq.com', '网易': 'https://www.163.com', '新浪': 'https://www.sina.com.cn',
  '搜狐': 'https://www.sohu.com', '凤凰': 'https://www.ifeng.com', '腾讯': 'https://www.qq.com',
  '优酷': 'https://www.youku.com', '爱奇艺': 'https://www.iqiyi.com', '腾讯视频': 'https://v.qq.com',
  '芒果TV': 'https://www.mgtv.com', '央视': 'https://www.cctv.com', '头条': 'https://www.toutiao.com',
  '网易云音乐': 'https://music.163.com', 'QQ音乐': 'https://y.qq.com', '酷狗': 'https://www.kugou.com',
  '酷我': 'https://www.kuwo.cn', '全民K歌': 'https://kg.qq.com', '虎牙': 'https://www.huya.com',
  '斗鱼': 'https://www.douyu.com', 'YY': 'https://www.yy.com', '起点': 'https://www.qidian.com',
  '晋江': 'https://www.jjwxc.net', '微信读书': 'https://weread.qq.com', '掌阅': 'https://www.zhangyue.com',
  'QQ邮箱': 'https://mail.qq.com', '163邮箱': 'https://mail.163.com', '126邮箱': 'https://mail.126.com',
  'Gmail': 'https://mail.google.com', 'Outlook': 'https://outlook.live.com',
  '高德': 'https://ditu.amap.com', '百度地图': 'https://map.baidu.com', '腾讯地图': 'https://map.qq.com',
  '滴滴': 'https://www.didiglobal.com', '美团': 'https://www.meituan.com', '饿了么': 'https://www.ele.me',
  '大众点评': 'https://www.dianping.com', '携程': 'https://www.ctrip.com', '去哪儿': 'https://www.qunar.com',
  '飞猪': 'https://www.fliggy.com', '马蜂窝': 'https://www.mafengwo.cn', '途牛': 'https://www.tuniu.com',
  '同程': 'https://www.ly.com', '贝壳': 'https://www.ke.com', '链家': 'https://www.lianjia.com',
  '安居客': 'https://www.anjuke.com', '房天下': 'https://www.fang.com', '58同城': 'https://www.58.com',
  '赶集': 'https://www.ganji.com', '闲鱼': 'https://www.xianyu.com', '转转': 'https://www.zhuanzhuan.com',
  '瓜子': 'https://www.guazi.com', '小米': 'https://www.mi.com', '华为': 'https://www.huawei.com',
  '苹果': 'https://www.apple.com.cn', '三星': 'https://www.samsung.com/cn', 'OPPO': 'https://www.oppo.com',
  'vivo': 'https://www.vivo.com', '荣耀': 'https://www.hihonor.com', '一加': 'https://www.oneplus.com',
  '魅族': 'https://www.meizu.com', '联想': 'https://www.lenovo.com.cn', '微软': 'https://www.microsoft.com/zh-cn',
  'GitHub': 'https://github.com', '码云': 'https://gitee.com', 'GitLab': 'https://gitlab.com',
  'StackOverflow': 'https://stackoverflow.com', 'CSDN': 'https://www.csdn.net', '掘金': 'https://juejin.cn',
  '博客园': 'https://www.cnblogs.com', '开源中国': 'https://www.oschina.net', 'V2EX': 'https://www.v2ex.com',
  'SegmentFault': 'https://segmentfault.com', '简书': 'https://www.jianshu.com', '语雀': 'https://www.yuque.com',
  '石墨': 'https://shimo.im', '腾讯文档': 'https://docs.qq.com', '金山文档': 'https://www.kdocs.cn',
  '飞书': 'https://www.feishu.cn', '钉钉': 'https://www.dingtalk.com', '企业微信': 'https://work.weixin.qq.com',
  '腾讯会议': 'https://meeting.tencent.com', 'Zoom': 'https://zoom.us', '阿里云': 'https://www.aliyun.com',
  '腾讯云': 'https://cloud.tencent.com', '华为云': 'https://www.huaweicloud.com', '百度云': 'https://cloud.baidu.com',
  '七牛': 'https://www.qiniu.com', 'AWS': 'https://aws.amazon.com', 'Azure': 'https://azure.microsoft.com',
  'Docker': 'https://www.docker.com', 'npm': 'https://www.npmjs.com', 'Figma': 'https://www.figma.com',
  'Sketch': 'https://www.sketch.com', '墨刀': 'https://modao.cc', '蓝湖': 'https://lanhuapp.com',
  '即时设计': 'https://js.design', 'Canva': 'https://www.canva.cn', 'WPS': 'https://www.wps.cn',
  'Office': 'https://www.office.com', 'ProcessOn': 'https://www.processon.com', '百度脑图': 'https://naotu.baidu.com',
  'XMind': 'https://www.xmind.cn', '幕布': 'https://mubu.com', '印象笔记': 'https://www.yinxiang.com',
  '有道云笔记': 'https://note.youdao.com', 'Notion': 'https://www.notion.so', 'OneNote': 'https://www.onenote.com',
  '滴答清单': 'https://dida365.com', 'Trello': 'https://trello.com', 'Asana': 'https://asana.com',
  'Jira': 'https://www.atlassian.com/software/jira', '禅道': 'https://www.zentao.net',
  'Teambition': 'https://www.teambition.com', 'Tower': 'https://tower.im', 'Axure': 'https://www.axure.com',
  '支付宝': 'https://www.alipay.com', '微信支付': 'https://pay.weixin.qq.com', '云闪付': 'https://www.95516.com',
  '京东支付': 'https://www.jdpay.com', 'PayPal': 'https://www.paypal.com', 'Stripe': 'https://stripe.com',
  '工商银行': 'https://www.icbc.com.cn', '建设银行': 'https://www.ccb.com', '农业银行': 'https://www.abchina.com',
  '中国银行': 'https://www.boc.cn', '招商银行': 'https://www.cmbchina.com', '交通银行': 'https://www.bankcomm.com',
  '邮储银行': 'https://www.psbc.com', '中信银行': 'https://www.citicbank.com', '光大银行': 'https://www.cebbank.com',
  '民生银行': 'https://www.cmbc.com.cn', '平安银行': 'https://bank.pingan.com', '浦发银行': 'https://www.spdb.com.cn',
  '兴业银行': 'https://www.cib.com.cn', '北京银行': 'https://www.bankofbeijing.com.cn', '上海银行': 'https://www.bosc.cn',
  '阿里图标': 'https://www.iconfont.cn', 'Iconfont': 'https://www.iconfont.cn', 'FontAwesome': 'https://fontawesome.com',
  '剪映': 'https://www.capcut.cn', '必剪': 'https://bcut.bilibili.cn', '美图秀秀': 'https://pc.meitu.com',
  '站酷': 'https://www.zcool.com.cn', 'Dribbble': 'https://dribbble.com', 'Behance': 'https://www.behance.net',
  'Pinterest': 'https://www.pinterest.com', '花瓣': 'https://huaban.com', '500px': 'https://500px.com',
  '视觉中国': 'https://www.vcg.com', '图虫': 'https://tuchong.com', '极客时间': 'https://time.geekbang.org',
  '得到': 'https://www.igetget.com', '樊登读书': 'https://www.dushu365.com', '喜马拉雅': 'https://www.ximalaya.com',
  '荔枝': 'https://www.lizhi.fm', '蜻蜓': 'https://www.qingting.fm', '企鹅FM': 'https://fm.qq.com',
  '移动': 'https://www.10086.cn', '联通': 'https://www.10010.com', '电信': 'https://www.189.cn',
  '腾讯问卷': 'https://wj.qq.com', '问卷星': 'https://www.wjx.cn', '金数据': 'https://jinshuju.net',
  'ECharts': 'https://echarts.apache.org', 'D3': 'https://d3js.org', 'Chart.js': 'https://www.chartjs.org',
  'Redis': 'https://redis.io', 'MongoDB': 'https://www.mongodb.com', 'MySQL': 'https://www.mysql.com',
  'Nginx': 'https://nginx.org', 'Apache': 'https://www.apache.org', 'Spring': 'https://spring.io',
  'Vue': 'https://vuejs.org', 'React': 'https://react.dev', 'Angular': 'https://angular.io',
  'Tailwind': 'https://tailwindcss.com', 'Bootstrap': 'https://getbootstrap.com', 'Element': 'https://element.eleme.io',
  'Ant': 'https://ant.design', 'Vuetify': 'https://vuetifyjs.com', 'Vant': 'https://vant-ui.github.io',
  'TDesign': 'https://tdesign.tencent.com', 'Arco': 'https://arco.design'
};
var BUILTIN_ICON_IDS = new Set(['home','briefcase','film','plus','plus-square','settings','star','grid','heart','music','camera','globe','book','coffee','shopping-bag','trash','edit','smile','zap','image','map-pin','pen-tool','search','x','check','folder','gamepad','airplane','car','monitor','dollar','clipboard','cloud','bell','phone','mail','sun','tv','code','watch','umbrella','video','calendar','clock','award','bar-chart','box','briefcase2','cast','chrome','command','copy','cpu','crosshair','disc','download','external-link','eye','fast-forward','feather','file','flag','hash','headphones','help-circle','inbox','layers','link','list','loader','lock','log-in','log-out','map','maximize','mic','minimize','moon','more-horizontal','more-vertical','move','paperclip','pause','pie-chart','play','pocket','power','printer','radio','refresh-cw','save','scissors','share','shield','shopping-cart','shuffle','sidebar','slider','speaker','square','stop','sunrise','sunset','tablet','tag','target','terminal','thermometer','thumbs-down','thumbs-up','toggle-left','toggle-right','tool','trash-2','trending-up','trending-down','triangle','truck','type','upload','user','users','voicemail','volume','wifi','b-honghui','c-tupian','b-aitger']);

/* ===== 原始数据（不可修改） ===== */
var defaultListShengHuo = [
      {"url":"https://weixin.qq.com/","iconId":"","imgSrc":"https://raw.giteeusercontent.com/lanzaong/fly/raw/main/icon/weixin.webp","name":"微信"},
      {"url":"https://www.doubao.com/","iconId":"","imgSrc":"https://raw.giteeusercontent.com/lanzaong/fly/raw/main/icon/doubao.webp","name":"豆包"},
      {"url":"http://www.qmcc.cc/","iconId":"","imgSrc":"https://raw.giteeusercontent.com/lanzaong/fly/raw/main/icon/b-ai.webp","name":"AI大全"},
      {"url":"https://jiankang.baidu.com/","iconId":"","imgSrc":"https://raw.giteeusercontent.com/lanzaong/fly/raw/main/icon/b-jiankang.webp","name":"百度健康"},
      {"url":"https://www.qishui.com/","iconId":"qishuiyinle","imgSrc":"https://raw.giteeusercontent.com/lanzaong/fly/raw/main/icon/qishuiyinle.webp","name":"汽水音乐"},
      {"url":"https://taobao.com","iconId":"","imgSrc":"https://raw.giteeusercontent.com/lanzaong/fly/raw/main/icon/tb.webp","name":"淘宝"},
      {"url":"https://jd.com","iconId":"","imgSrc":"https://raw.giteeusercontent.com/lanzaong/fly/raw/main/icon/jingdong.webp","name":"京东"},
      {"url":"https://douban.com/","iconId":"","imgSrc":"https://raw.giteeusercontent.com/lanzaong/fly/raw/main/icon/db.webp","name":"豆瓣"},
      {"url":"https://www.dianping.com/","iconId":"","imgSrc":"https://raw.giteeusercontent.com/lanzaong/fly/raw/main/icon/dazhongdianping.webp","name":"大众点评"},
      {"url":"https://hz.58.com/","iconId":"","imgSrc":"https://raw.giteeusercontent.com/lanzaong/fly/raw/main/icon/b-tongcheng.webp","name":"58同城"},
      {"url":"https://xiaohongshu.com","iconId":"","imgSrc":"https://raw.giteeusercontent.com/lanzaong/fly/raw/main/icon/xiaohongshu.webp","name":"小红书"},
      {"url":"https://kuaidi100.com/","iconId":"","imgSrc":"https://raw.giteeusercontent.com/lanzaong/fly/raw/main/icon/b-100.webp","name":"快递100"},
      {"url":"https://dongchedi.com/","iconId":"","imgSrc":"https://raw.giteeusercontent.com/lanzaong/fly/raw/main/icon/dongchedi.webp","name":"懂车帝"},
      {"url":"https://www.goofish.com/","iconId":"","imgSrc":"https://raw.giteeusercontent.com/lanzaong/fly/raw/main/icon/xianyu.webp","name":"闲鱼"},
      {"url":"https://music.migu.cn/","iconId":"","imgSrc":"https://raw.giteeusercontent.com/lanzaong/fly/raw/main/icon/b-miguyinle.webp","name":"咪咕音乐"},
      {"url":"https://ctrip.com","iconId":"","imgSrc":"https://raw.giteeusercontent.com/lanzaong/fly/raw/main/icon/xiechenglvhang.webp","name":"携程"},
      {"url":"https://vip.com/","iconId":"","imgSrc":"https://raw.giteeusercontent.com/lanzaong/fly/raw/main/icon/weipinhui.webp","name":"唯品会"},
      {"url":"https://weibo.com/","iconId":"b-weibo","imgSrc":"https://raw.giteeusercontent.com/lanzaong/fly/raw/main/icon/b-weibo.webp","name":"微博"},
      {"url":"https://www.sf-express.com/","iconId":"","imgSrc":"https://raw.giteeusercontent.com/lanzaong/fly/raw/main/icon/shunfeng.webp","name":"顺丰"},
      {"url":"https://mail.163.com/","iconId":"","imgSrc":"https://raw.giteeusercontent.com/lanzaong/fly/raw/main/icon/a-163youxiang.webp","name":"163邮箱"},
      {"url":"https://www.tmall.com/","iconId":"","imgSrc":"https://raw.giteeusercontent.com/lanzaong/fly/raw/main/icon/b-tianmao.webp","name":"天猫"},
      {"url":"https://tv.cctv.com/","iconId":"","imgSrc":"https://raw.giteeusercontent.com/lanzaong/fly/raw/main/icon/yangshipinchaotuoyuan.webp","name":"CCTV"},
      {"url":"https://ximalaya.com","iconId":"","imgSrc":"https://raw.giteeusercontent.com/lanzaong/fly/raw/main/icon/ximalaya.webp","name":"喜马拉雅"},
      {"url":"https://www.zhihu.com/","iconId":"","imgSrc":"https://raw.giteeusercontent.com/lanzaong/fly/raw/main/icon/b-zhihu.webp","name":"知乎"},
      {"url":"https://www.12306.cn/","iconId":"","imgSrc":"https://raw.giteeusercontent.com/lanzaong/fly/raw/main/icon/Appicns_12306.webp","name":"12306"},
      {"url":"https://kugou.com","iconId":"","imgSrc":"https://raw.giteeusercontent.com/lanzaong/fly/raw/main/icon/kugou.webp","name":"酷狗"},
      {"url":"https://y.qq.com/","iconId":"","imgSrc":"https://raw.giteeusercontent.com/lanzaong/fly/raw/main/icon/b-qqyinyue.webp","name":"QQ音乐"},
      {"url":"https://v.qq.com","iconId":"","imgSrc":"https://raw.giteeusercontent.com/lanzaong/fly/raw/main/icon/tencent.webp","name":"腾讯视频"},
      {"url":"https://miguvideo.com/","iconId":"","imgSrc":"https://raw.giteeusercontent.com/lanzaong/fly/raw/main/icon/b-migushi.webp","name":"咪咕视频"},
      {"url":"https://iqiyi.com","iconId":"","imgSrc":"https://raw.giteeusercontent.com/lanzaong/fly/raw/main/icon/iqiyi.webp","name":"爱奇艺"},
      {"url":"https://bilibili.com","iconId":"","imgSrc":"https://raw.giteeusercontent.com/lanzaong/fly/raw/main/icon/bilibili.webp","name":"哔哩哔哩"},
      {"url":"https://Douyin.com","iconId":"","imgSrc":"https://raw.giteeusercontent.com/lanzaong/fly/raw/main/icon/douyin.webp","name":"抖音"},
      {"url":"https://kuaishou.com/","iconId":"","imgSrc":"https://raw.giteeusercontent.com/lanzaong/fly/raw/main/icon/kuaishou.webp","name":"快手"},
      {"url":"https://news.qq.com/","iconId":"","imgSrc":"https://raw.giteeusercontent.com/lanzaong/fly/raw/main/icon/b-tengxunxinwen.webp","name":"腾讯新闻"},
      {"url":"https://mgtv.com","iconId":"","imgSrc":"https://raw.giteeusercontent.com/lanzaong/fly/raw/main/icon/mangguoTV.webp","name":"芒果TV"},
      {"url":"https://youku.com","iconId":"","imgSrc":"https://raw.giteeusercontent.com/lanzaong/fly/raw/main/icon/youku.webp","name":"优酷"},
      {"url":"https://mail.qq.com/","iconId":"","imgSrc":"https://raw.giteeusercontent.com/lanzaong/fly/raw/main/icon/b-qqyouxiang.webp","name":"QQ邮箱"}
    ];
var defaultListBanGong = [
      {"url":"https://guangtoulao.github.io/fenl/zqzb/ys.html","iconId":"","imgSrc":"https://raw.giteeusercontent.com/lanzaong/fly/raw/main/icon/b-yingshi.webp","name":"影视导航"},
      {"url":"https://www.iconfont.cn/","iconId":"","imgSrc":"https://raw.giteeusercontent.com/lanzaong/fly/raw/main/icon/a-yemian11.webp","name":"阿里图库"},
      {"url":"https://www.trae.cn/","iconId":"","imgSrc":"https://lf-cdn.trae.com.cn/obj/trae-com-cn/trae_website_prod_cn/favicon.png","name":"trae work"},
      {"url":"https://steampp.net/","iconId":"","imgSrc":"https://raw.giteeusercontent.com/lanzaong/fly/raw/main/icon/watt.webp","name":"瓦特加速"},
      {"url":"https://kstore.cc/","iconId":"","imgSrc":"https://raw.giteeusercontent.com/lanzaong/fly/raw/main/icon/kaisu.webp","name":"凯速网"},
      {"url":"https://github.com/fxsound2/fxsound-app","iconId":"","imgSrc":"https://raw.giteeusercontent.com/lanzaong/fly/raw/main/icon/yinxiao.webp","name":"音效调节"},
      {"url":"https://mt2.cn/download/","iconId":"","imgSrc":"https://raw.giteeusercontent.com/lanzaong/fly/raw/main/icon/b-mt.webp","name":"MT管理器"},
      {"url":"https://guangtoulao.github.io/fenl/","iconId":"","imgSrc":"https://raw.giteeusercontent.com/lanzaong/fly/raw/main/icon/b-xiugai.webp","name":"修图工具"},
      {"url":"https://github.com/","iconId":"","imgSrc":"https://raw.giteeusercontent.com/lanzaong/fly/raw/main/icon/github.webp","name":"github"},
      {"url":"https://www.neatdownloadmanager.com/index.php/en","iconId":"","imgSrc":"https://raw.giteeusercontent.com/lanzaong/fly/raw/main/icon/ndm.webp","name":"NDM下载器"},
      {"url":"https://guangtoulao.github.io/fenl/zqzb/dns.html","iconId":"","imgSrc":"https://raw.giteeusercontent.com/lanzaong/fly/raw/main/icon/dns-hei.webp","name":"域名申请"},
      {"url":"https://guangtoulao.github.io/fenl/zqzb/zxgj.html","iconId":"b-zaixian","imgSrc":"https://raw.giteeusercontent.com/lanzaong/fly/raw/main/icon/b-zaixian.webp","name":"在线工具"},
      {"url":"https://www.52pojie.cn/","iconId":"","imgSrc":"https://raw.giteeusercontent.com/lanzaong/fly/raw/main/icon/b-pojie.webp","name":"吾爱破解"},
      {"url":"https://www.yxzhi.com/","iconId":"","imgSrc":"https://raw.giteeusercontent.com/lanzaong/fly/raw/main/icon/b-yazi.webp","name":"鸭先知"},
      {"url":"https://tugaigai.com/online_ps/","iconId":"i","imgSrc":"https://raw.giteeusercontent.com/lanzaong/fly/raw/main/icon/AdobePs.webp","name":"PS修图"},
      {"url":"https://qiushui.vip/","iconId":"","imgSrc":"https://raw.giteeusercontent.com/lanzaong/fly/raw/main/icon/qiushui.webp","name":"秋水网"},
      {"url":"https://adzhp.cc/","iconId":"","imgSrc":"https://raw.giteeusercontent.com/lanzaong/fly/raw/main/icon/A.webp","name":"爱达杂货铺"},
      {"url":"https://pan.baidu.com/","iconId":"","imgSrc":"https://raw.giteeusercontent.com/lanzaong/fly/raw/main/icon/baiduwangpan.webp","name":"百度网盘"},
      {"url":"https://drivergenius.com/","iconId":"","imgSrc":"https://raw.giteeusercontent.com/lanzaong/fly/raw/main/icon/b-qudongjingling.webp","name":"驱动精灵"},
      {"url":"https://huorong.cn/","iconId":"","imgSrc":"https://raw.giteeusercontent.com/lanzaong/fly/raw/main/icon/b-huorong.webp","name":"火绒安全"},
      {"url":"https://4399.com/","iconId":"","imgSrc":"https://raw.giteeusercontent.com/lanzaong/fly/raw/main/icon/b-youxi.webp","name":"4399游戏"},
      {"url":"https://www.rjshe.com/","iconId":"","imgSrc":"https://raw.giteeusercontent.com/lanzaong/fly/raw/main/icon/changyongruanjian.webp","name":"软件社"}
    ];
var defaultApiList = [
    {name:'君子兰',url:'https://cwys.qzz.io/api.json',lineColor:'#e84393'},
    {name:'饭太硬',url:'http://fty.xxooo.cf/tv',lineColor:'#3498db'},
    {name:'潇洒',url:'https://qist.wyfc.qzz.io/xiaosa/api.json',lineColor:'#f39c12'},
    {name:'摸鱼',url:'http://www.小不点.com',lineColor:'#f1c40f'},
    {name:'王二小',url:'http://tvbox.王二小放牛娃.top',lineColor:'#cddc39'},
    {name:'小虎斑',url:'http://hb.小虎斑.site:25252/仅供测试',lineColor:'#2ecc71'},
    {name:'点播',url:'https://xpb.mhfs.eu.org/ZJ/XPB/api.json',lineColor:'#9932CC'},
    {name:'多多',url:'https://www.iyouhun.com/tv/duo',lineColor:'#e84393'},
    {name:'嗷呜',url:'https://9763.kstore.space/aowu.json',lineColor:'#ffbc23'}
  ];
var randomColorArr=['#e84393','#3498db','#f39c12','#f1c40f','#cddc39','#2ecc71','#9932CC','#ffbc23','#9b59b6','#1abc9c','#e74c3c','#3498db'];

var defaultBgLibrary = [
    /* === 自然风景 (nature) === */
    {name:'自然1',url:'https://img2.baidu.com/it/u=399019925,2499719398&fm=253&fmt=auto&app=138&f=JPEG?w=889&h=500',type:'image',cat:'nature'},
    {name:'自然2',url:'https://raw.giteeusercontent.com/lanzaong/lan/raw/master/icon/bz2.webp',type:'image',cat:'nature'},
    {name:'自然3',url:'https://raw.giteeusercontent.com/lanzaong/lan/raw/master/icon/bz3.webp',type:'image',cat:'nature'},
    {name:'自然4',url:'https://raw.giteeusercontent.com/lanzaong/lan/raw/master/icon/bz4.webp',type:'image',cat:'nature'},
    {name:'自然5',url:'https://raw.giteeusercontent.com/lanzaong/lan/raw/master/icon/bz5.webp',type:'image',cat:'nature'},
    {name:'自然6',url:'https://raw.giteeusercontent.com/lanzaong/lan/raw/master/icon/bz6.webp',type:'image',cat:'nature'},
    {name:'自然7',url:'https://raw.giteeusercontent.com/lanzaong/lan/raw/master/icon/bz7.webp',type:'image',cat:'nature'},
    {name:'自然8',url:'https://raw.giteeusercontent.com/lanzaong/lan/raw/master/icon/bz8.webp',type:'image',cat:'nature'},
    {name:'自然9',url:'https://raw.giteeusercontent.com/lanzaong/lan/raw/master/icon/bz9.webp',type:'image',cat:'nature'},
    {name:'自然10',url:'https://raw.giteeusercontent.com/lanzaong/lan/raw/master/icon/bz10.webp',type:'image',cat:'nature'},
    {name:'自然11',url:'https://raw.giteeusercontent.com/lanzaong/lan/raw/master/icon/bz11.webp',type:'image',cat:'nature'},
    {name:'自然12',url:'https://raw.giteeusercontent.com/lanzaong/lan/raw/master/icon/bz12.webp',type:'image',cat:'nature'},
    {name:'自然13',url:'https://raw.giteeusercontent.com/lanzaong/lan/raw/master/icon/bz13.webp',type:'image',cat:'nature'},
    {name:'自然14',url:'https://raw.giteeusercontent.com/lanzaong/lan/raw/master/icon/bz14.webp',type:'image',cat:'nature'},
    {name:'自然15',url:'https://raw.giteeusercontent.com/lanzaong/lan/raw/master/icon/bz15.webp',type:'image',cat:'nature'},
    {name:'自然16',url:'https://raw.giteeusercontent.com/lanzaong/lan/raw/master/icon/bz16.webp',type:'image',cat:'nature'},
    {name:'自然17',url:'https://raw.giteeusercontent.com/lanzaong/lan/raw/master/icon/bz17.webp',type:'image',cat:'nature'},
    {name:'自然18',url:'https://raw.giteeusercontent.com/lanzaong/lan/raw/master/icon/bz18.webp',type:'image',cat:'nature'},
    {name:'自然19',url:'https://raw.giteeusercontent.com/lanzaong/lan/raw/master/icon/bz19.webp',type:'image',cat:'nature'},
    {name:'自然20',url:'https://raw.giteeusercontent.com/lanzaong/lan/raw/master/icon/bz20.webp',type:'image',cat:'nature'},
    {name:'自然21',url:'https://raw.giteeusercontent.com/lanzaong/lan/raw/master/icon/bz21.webp',type:'image',cat:'nature'},
    {name:'自然22',url:'https://raw.giteeusercontent.com/lanzaong/lan/raw/master/icon/bz22.webp',type:'image',cat:'nature'},
    {name:'自然23',url:'https://raw.giteeusercontent.com/lanzaong/lan/raw/master/icon/bz23.webp',type:'image',cat:'nature'},
    {name:'自然24',url:'https://raw.giteeusercontent.com/lanzaong/lan/raw/master/icon/bz24.webp',type:'image',cat:'nature'},
    {name:'自然25',url:'https://raw.giteeusercontent.com/lanzaong/lan/raw/master/icon/bz25.webp',type:'image',cat:'nature'},
    {name:'自然26',url:'https://raw.giteeusercontent.com/lanzaong/lan/raw/master/icon/bz26.webp',type:'image',cat:'nature'},
    {name:'自然27',url:'https://raw.giteeusercontent.com/lanzaong/lan/raw/master/icon/bz27.webp',type:'image',cat:'nature'},
    {name:'自然28',url:'https://raw.giteeusercontent.com/lanzaong/lan/raw/master/icon/bz28.webp',type:'image',cat:'nature'},
    {name:'自然29',url:'https://raw.giteeusercontent.com/lanzaong/lan/raw/master/icon/bz29.webp',type:'image',cat:'nature'},
    {name:'自然30',url:'https://raw.giteeusercontent.com/lanzaong/lan/raw/master/icon/bz30.webp',type:'image',cat:'nature'},
    {name:'自然31',url:'https://raw.giteeusercontent.com/lanzaong/lan/raw/master/icon/bz31.webp',type:'image',cat:'nature'},
    {name:'自然32',url:'https://raw.giteeusercontent.com/lanzaong/lan/raw/master/icon/bz32.webp',type:'image',cat:'nature'},
    {name:'自然33',url:'https://raw.giteeusercontent.com/lanzaong/lan/raw/master/icon/bz33.webp',type:'image',cat:'nature'},
    {name:'自然34',url:'https://raw.giteeusercontent.com/lanzaong/lan/raw/master/icon/bz34.webp',type:'image',cat:'nature'},
    {name:'自然35',url:'https://raw.giteeusercontent.com/lanzaong/lan/raw/master/icon/bz35.webp',type:'image',cat:'nature'},
    {name:'自然36',url:'https://raw.giteeusercontent.com/lanzaong/lan/raw/master/icon/bz36.webp',type:'image',cat:'nature'},
    {name:'自然37',url:'https://raw.giteeusercontent.com/lanzaong/lan/raw/master/icon/bz37.webp',type:'image',cat:'nature'},
    {name:'自然38',url:'https://raw.giteeusercontent.com/lanzaong/lan/raw/master/icon/bz38.webp',type:'image',cat:'nature'},
    {name:'自然39',url:'https://raw.giteeusercontent.com/lanzaong/lan/raw/master/icon/bz39.webp',type:'image',cat:'nature'},
    {name:'自然40',url:'https://raw.giteeusercontent.com/lanzaong/lan/raw/master/icon/bz40.webp',type:'image',cat:'nature'},
    {name:'自然41',url:'https://raw.giteeusercontent.com/lanzaong/lan/raw/master/icon/bz41.webp',type:'image',cat:'nature'},
    {name:'自然42',url:'https://raw.giteeusercontent.com/lanzaong/lan/raw/master/icon/bz42.webp',type:'image',cat:'nature'},
    {name:'自然43',url:'https://raw.giteeusercontent.com/lanzaong/lan/raw/master/icon/bz43.webp',type:'image',cat:'nature'},
    {name:'自然44',url:'https://raw.giteeusercontent.com/lanzaong/lan/raw/master/icon/bz44.webp',type:'image',cat:'nature'},
    {name:'自然45',url:'https://raw.giteeusercontent.com/lanzaong/lan/raw/master/icon/bz45.webp',type:'image',cat:'nature'},
    {name:'自然46',url:'https://raw.giteeusercontent.com/lanzaong/lan/raw/master/icon/bz46.webp',type:'image',cat:'nature'},
    {name:'自然47',url:'https://img1.baidu.com/it/u=4040498816,3909610692&fm=253&fmt=auto&app=138&f=JPEG?w=1422&h=800',type:'image',cat:'nature'},
    {name:'自然48',url:'https://raw.giteeusercontent.com/lanzaong/lan/raw/master/icon/bz48.webp',type:'image',cat:'nature'},
    {name:'自然49',url:'https://raw.giteeusercontent.com/lanzaong/lan/raw/master/icon/bz49.webp',type:'image',cat:'nature'},
    {name:'自然50',url:'https://raw.giteeusercontent.com/lanzaong/lan/raw/master/icon/bz50.webp',type:'image',cat:'nature'},
    {name:'自然51',url:'https://raw.giteeusercontent.com/lanzaong/lan/raw/master/icon/bz51.webp',type:'image',cat:'nature'},
    {name:'自然52',url:'https://raw.giteeusercontent.com/lanzaong/lan/raw/master/icon/bz52.webp',type:'image',cat:'nature'},
    {name:'自然53',url:'https://raw.giteeusercontent.com/lanzaong/lan/raw/master/icon/bz53.webp',type:'image',cat:'nature'},
    {name:'自然54',url:'https://raw.giteeusercontent.com/lanzaong/lan/raw/master/icon/bz54.webp',type:'image',cat:'nature'},
    {name:'自然55',url:'https://raw.giteeusercontent.com/lanzaong/lan/raw/master/icon/bz55.webp',type:'image',cat:'nature'},
    {name:'自然56',url:'https://raw.giteeusercontent.com/lanzaong/lan/raw/master/icon/bz56.webp',type:'image',cat:'nature'},
    {name:'自然57',url:'https://raw.giteeusercontent.com/lanzaong/lan/raw/master/icon/bz57.webp',type:'image',cat:'nature'},
    {name:'自然58',url:'https://raw.giteeusercontent.com/lanzaong/lan/raw/master/icon/bz58.webp',type:'image',cat:'nature'},
    {name:'自然59',url:'https://raw.giteeusercontent.com/lanzaong/lan/raw/master/icon/bz59.webp',type:'image',cat:'nature'},
    {name:'自然60',url:'https://raw.giteeusercontent.com/lanzaong/lan/raw/master/icon/bz60.webp',type:'image',cat:'nature'},
    {name:'自然61',url:'https://raw.giteeusercontent.com/lanzaong/lan/raw/master/icon/bz61.webp',type:'image',cat:'nature'},
    {name:'自然62',url:'https://raw.giteeusercontent.com/lanzaong/lan/raw/master/icon/bz62.webp',type:'image',cat:'nature'},
    {name:'自然63',url:'https://raw.giteeusercontent.com/lanzaong/lan/raw/master/icon/bz63.webp',type:'image',cat:'nature'},
    {name:'自然64',url:'https://raw.giteeusercontent.com/lanzaong/lan/raw/master/icon/bz64.webp',type:'image',cat:'nature'},
    {name:'自然65',url:'https://raw.giteeusercontent.com/lanzaong/lan/raw/master/icon/bz65.webp',type:'image',cat:'nature'},
    {name:'自然66',url:'https://raw.giteeusercontent.com/lanzaong/lan/raw/master/icon/bz66.webp',type:'image',cat:'nature'},
    {name:'自然67',url:'https://raw.giteeusercontent.com/lanzaong/lan/raw/master/icon/bz67.webp',type:'image',cat:'nature'},
    {name:'自然68',url:'https://raw.giteeusercontent.com/lanzaong/lan/raw/master/icon/bz68.webp',type:'image',cat:'nature'},
    {name:'自然69',url:'https://raw.giteeusercontent.com/lanzaong/lan/raw/master/icon/bz69.webp',type:'image',cat:'nature'},
    {name:'自然70',url:'https://img2.baidu.com/it/u=3658457710,1798349027&fm=253&fmt=auto&app=120&f=JPEG?w=1422&h=800',type:'image',cat:'nature'},
    {name:'自然71',url:'https://raw.giteeusercontent.com/lanzaong/lan/raw/master/icon/bz71.webp',type:'image',cat:'nature'},
    {name:'自然72',url:'https://raw.giteeusercontent.com/lanzaong/lan/raw/master/icon/bz72.webp',type:'image',cat:'nature'},
    {name:'自然73',url:'https://raw.giteeusercontent.com/lanzaong/lan/raw/master/icon/bz73.webp',type:'image',cat:'nature'},
    {name:'自然74',url:'https://raw.giteeusercontent.com/lanzaong/lan/raw/master/icon/bz74.webp',type:'image',cat:'nature'},
    {name:'自然75',url:'https://raw.giteeusercontent.com/lanzaong/lan/raw/master/icon/bz75.webp',type:'image',cat:'nature'},
    {name:'自然76',url:'https://raw.giteeusercontent.com/lanzaong/lan/raw/master/icon/bz76.webp',type:'image',cat:'nature'},
    {name:'自然77',url:'https://raw.giteeusercontent.com/lanzaong/lan/raw/master/icon/bz77.webp',type:'image',cat:'nature'},
    {name:'自然78',url:'https://raw.giteeusercontent.com/lanzaong/lan/raw/master/icon/bz78.webp',type:'image',cat:'nature'},
    {name:'自然79',url:'https://raw.giteeusercontent.com/lanzaong/lan/raw/master/icon/bz79.webp',type:'image',cat:'nature'},
    {name:'自然80',url:'https://raw.giteeusercontent.com/lanzaong/lan/raw/master/icon/bz80.webp',type:'image',cat:'nature'},
    {name:'自然81',url:'https://raw.giteeusercontent.com/lanzaong/lan/raw/master/icon/bz81.webp',type:'image',cat:'nature'},
    {name:'自然82',url:'https://raw.giteeusercontent.com/lanzaong/lan/raw/master/icon/bz82.webp',type:'image',cat:'nature'},
    {name:'自然83',url:'https://raw.giteeusercontent.com/lanzaong/lan/raw/master/icon/bz83.webp',type:'image',cat:'nature'},
    {name:'自然84',url:'https://raw.giteeusercontent.com/lanzaong/lan/raw/master/icon/bz84.webp',type:'image',cat:'nature'},
    {name:'自然85',url:'https://raw.giteeusercontent.com/lanzaong/lan/raw/master/icon/bz85.webp',type:'image',cat:'nature'},
    {name:'自然86',url:'https://raw.giteeusercontent.com/lanzaong/lan/raw/master/icon/bz86.webp',type:'image',cat:'nature'},
    {name:'自然87',url:'https://raw.giteeusercontent.com/lanzaong/lan/raw/master/icon/bz87.webp',type:'image',cat:'nature'},
    {name:'自然88',url:'https://raw.giteeusercontent.com/lanzaong/lan/raw/master/icon/bz88.webp',type:'image',cat:'nature'},
    {name:'自然89',url:'https://raw.giteeusercontent.com/lanzaong/lan/raw/master/icon/bz89.webp',type:'image',cat:'nature'},
    /* === 城市建筑 (architecture) === */
    {name:'城市1',url:'https://raw.giteeusercontent.com/lanzaong/lan/raw/master/icons/cs/cs1.webp',type:'image',cat:'architecture'},
    {name:'城市2',url:'https://raw.giteeusercontent.com/lanzaong/lan/raw/master/icons/cs/cs2.webp',type:'image',cat:'architecture'},
    {name:'城市3',url:'https://raw.giteeusercontent.com/lanzaong/lan/raw/master/icons/cs/cs3.webp',type:'image',cat:'architecture'},
    {name:'城市4',url:'https://raw.giteeusercontent.com/lanzaong/lan/raw/master/icons/cs/cs4.webp',type:'image',cat:'architecture'},
    {name:'城市5',url:'https://raw.giteeusercontent.com/lanzaong/lan/raw/master/icons/cs/cs5.webp',type:'image',cat:'architecture'},
    {name:'城市6',url:'https://raw.giteeusercontent.com/lanzaong/lan/raw/master/icons/cs/cs6.webp',type:'image',cat:'architecture'},
    {name:'城市7',url:'https://raw.giteeusercontent.com/lanzaong/lan/raw/master/icons/cs/cs7.webp',type:'image',cat:'architecture'},
    {name:'城市8',url:'https://raw.giteeusercontent.com/lanzaong/lan/raw/master/icons/cs/cs8.webp',type:'image',cat:'architecture'},
    {name:'城市9',url:'https://raw.giteeusercontent.com/lanzaong/lan/raw/master/icons/cs/cs9.webp',type:'image',cat:'architecture'},
    {name:'城市10',url:'https://raw.giteeusercontent.com/lanzaong/lan/raw/master/icons/cs/cs10.webp',type:'image',cat:'architecture'},
    {name:'城市11',url:'https://raw.giteeusercontent.com/lanzaong/lan/raw/master/icons/cs/cs11.webp',type:'image',cat:'architecture'},
    {name:'城市12',url:'https://raw.giteeusercontent.com/lanzaong/lan/raw/master/icons/cs/cs12.webp',type:'image',cat:'architecture'},
    {name:'城市13',url:'https://raw.giteeusercontent.com/lanzaong/lan/raw/master/icons/cs/cs13.webp',type:'image',cat:'architecture'},
    {name:'城市14',url:'https://raw.giteeusercontent.com/lanzaong/lan/raw/master/icons/cs/cs14.webp',type:'image',cat:'architecture'},
    {name:'城市15',url:'https://raw.giteeusercontent.com/lanzaong/lan/raw/master/icons/cs/cs15.webp',type:'image',cat:'architecture'},
    {name:'城市16',url:'https://raw.giteeusercontent.com/lanzaong/lan/raw/master/icons/cs/cs16.webp',type:'image',cat:'architecture'},
    {name:'城市17',url:'https://raw.giteeusercontent.com/lanzaong/lan/raw/master/icons/cs/cs17.webp',type:'image',cat:'architecture'},
    {name:'城市18',url:'https://raw.giteeusercontent.com/lanzaong/lan/raw/master/icons/cs/cs18.webp',type:'image',cat:'architecture'},
    {name:'城市19',url:'https://raw.giteeusercontent.com/lanzaong/lan/raw/master/icons/cs/cs19.webp',type:'image',cat:'architecture'},
    {name:'城市20',url:'https://raw.giteeusercontent.com/lanzaong/lan/raw/master/icons/cs/cs20.webp',type:'image',cat:'architecture'},
    {name:'城市21',url:'https://raw.giteeusercontent.com/lanzaong/lan/raw/master/icons/cs/cs21.webp',type:'image',cat:'architecture'},
    {name:'城市22',url:'https://raw.giteeusercontent.com/lanzaong/lan/raw/master/icons/cs/cs22.webp',type:'image',cat:'architecture'},
    {name:'城市23',url:'https://raw.giteeusercontent.com/lanzaong/lan/raw/master/icons/cs/cs23.webp',type:'image',cat:'architecture'},
    {name:'城市24',url:'https://raw.giteeusercontent.com/lanzaong/lan/raw/master/icons/cs/cs24.webp',type:'image',cat:'architecture'},
    {name:'城市25',url:'https://raw.giteeusercontent.com/lanzaong/lan/raw/master/icons/cs/cs25.webp',type:'image',cat:'architecture'},
    {name:'城市26',url:'https://raw.giteeusercontent.com/lanzaong/lan/raw/master/icons/cs/cs26.webp',type:'image',cat:'architecture'},
    {name:'城市27',url:'https://raw.giteeusercontent.com/lanzaong/lan/raw/master/icons/cs/cs27.webp',type:'image',cat:'architecture'},
    {name:'城市28',url:'https://raw.giteeusercontent.com/lanzaong/lan/raw/master/icons/cs/cs28.webp',type:'image',cat:'architecture'},
    {name:'城市29',url:'https://raw.giteeusercontent.com/lanzaong/lan/raw/master/icons/cs/cs29.webp',type:'image',cat:'architecture'},
    {name:'城市30',url:'https://raw.giteeusercontent.com/lanzaong/lan/raw/master/icons/cs/cs30.webp',type:'image',cat:'architecture'},
    {name:'城市31',url:'https://raw.giteeusercontent.com/lanzaong/lan/raw/master/icons/cs/cs31.webp',type:'image',cat:'architecture'},
    {name:'城市32',url:'https://raw.giteeusercontent.com/lanzaong/lan/raw/master/icons/cs/cs32.webp',type:'image',cat:'architecture'},
    {name:'城市33',url:'https://raw.giteeusercontent.com/lanzaong/lan/raw/master/icons/cs/cs33.webp',type:'image',cat:'architecture'},
    {name:'城市34',url:'https://raw.giteeusercontent.com/lanzaong/lan/raw/master/icons/cs/cs34.webp',type:'image',cat:'architecture'},
    {name:'城市35',url:'https://raw.giteeusercontent.com/lanzaong/lan/raw/master/icons/cs/cs35.webp',type:'image',cat:'architecture'},
    {name:'城市36',url:'https://raw.giteeusercontent.com/lanzaong/lan/raw/master/icons/cs/cs36.webp',type:'image',cat:'architecture'},
    {name:'城市37',url:'https://raw.giteeusercontent.com/lanzaong/lan/raw/master/icons/cs/cs37.webp',type:'image',cat:'architecture'},
    {name:'城市38',url:'https://raw.giteeusercontent.com/lanzaong/lan/raw/master/icons/cs/cs38.webp',type:'image',cat:'architecture'},
    {name:'城市39',url:'https://raw.giteeusercontent.com/lanzaong/lan/raw/master/icons/cs/cs39.webp',type:'image',cat:'architecture'},
    {name:'城市40',url:'https://raw.giteeusercontent.com/lanzaong/lan/raw/master/icons/cs/cs40.webp',type:'image',cat:'architecture'},
    {name:'城市41',url:'https://raw.giteeusercontent.com/lanzaong/lan/raw/master/icons/cs/cs41.webp',type:'image',cat:'architecture'},
    {name:'城市42',url:'https://raw.giteeusercontent.com/lanzaong/lan/raw/master/icons/cs/cs42.webp',type:'image',cat:'architecture'},
    {name:'城市43',url:'https://raw.giteeusercontent.com/lanzaong/lan/raw/master/icons/cs/cs43.webp',type:'image',cat:'architecture'},
    {name:'城市44',url:'https://raw.giteeusercontent.com/lanzaong/lan/raw/master/icons/cs/cs44.webp',type:'image',cat:'architecture'},
    {name:'城市45',url:'https://raw.giteeusercontent.com/lanzaong/lan/raw/master/icons/cs/cs45.webp',type:'image',cat:'architecture'},
    {name:'城市46',url:'https://raw.giteeusercontent.com/lanzaong/lan/raw/master/icons/cs/cs46.webp',type:'image',cat:'architecture'},
    {name:'城市47',url:'https://raw.giteeusercontent.com/lanzaong/lan/raw/master/icons/cs/cs47.webp',type:'image',cat:'architecture'},
    {name:'城市48',url:'https://raw.giteeusercontent.com/lanzaong/lan/raw/master/icons/cs/cs48.webp',type:'image',cat:'architecture'},
    {name:'城市49',url:'https://raw.giteeusercontent.com/lanzaong/lan/raw/master/icons/cs/cs49.webp',type:'image',cat:'architecture'},
    {name:'城市50',url:'https://raw.giteeusercontent.com/lanzaong/lan/raw/master/icons/cs/cs50.webp',type:'image',cat:'architecture'},
    {name:'城市51',url:'https://raw.giteeusercontent.com/lanzaong/lan/raw/master/icons/cs/cs51.webp',type:'image',cat:'architecture'},
    {name:'城市52',url:'https://raw.giteeusercontent.com/lanzaong/lan/raw/master/icons/cs/cs52.webp',type:'image',cat:'architecture'},
    {name:'城市53',url:'https://raw.giteeusercontent.com/lanzaong/lan/raw/master/icons/cs/cs53.webp',type:'image',cat:'architecture'},
    {name:'城市54',url:'https://raw.giteeusercontent.com/lanzaong/lan/raw/master/icons/cs/cs54.webp',type:'image',cat:'architecture'},
    {name:'城市55',url:'https://raw.giteeusercontent.com/lanzaong/lan/raw/master/icons/cs/cs55.webp',type:'image',cat:'architecture'},
    {name:'城市56',url:'https://raw.giteeusercontent.com/lanzaong/lan/raw/master/icons/cs/cs56.webp',type:'image',cat:'architecture'},
    {name:'城市57',url:'https://raw.giteeusercontent.com/lanzaong/lan/raw/master/icons/cs/cs57.webp',type:'image',cat:'architecture'},
    {name:'城市58',url:'https://raw.giteeusercontent.com/lanzaong/lan/raw/master/icons/cs/cs58.webp',type:'image',cat:'architecture'},
    {name:'城市59',url:'https://raw.giteeusercontent.com/lanzaong/lan/raw/master/icons/cs/cs59.webp',type:'image',cat:'architecture'},
    {name:'城市60',url:'https://raw.giteeusercontent.com/lanzaong/lan/raw/master/icons/cs/cs60.webp',type:'image',cat:'architecture'},
    {name:'城市61',url:'https://raw.giteeusercontent.com/lanzaong/lan/raw/master/icons/cs/cs61.webp',type:'image',cat:'architecture'},
    {name:'城市62',url:'https://raw.giteeusercontent.com/lanzaong/lan/raw/master/icons/cs/cs62.webp',type:'image',cat:'architecture'},
    {name:'城市63',url:'https://raw.giteeusercontent.com/lanzaong/lan/raw/master/icons/cs/cs63.webp',type:'image',cat:'architecture'},
    {name:'城市64',url:'https://raw.giteeusercontent.com/lanzaong/lan/raw/master/icons/cs/cs64.webp',type:'image',cat:'architecture'},
    {name:'城市65',url:'https://raw.giteeusercontent.com/lanzaong/lan/raw/master/icons/cs/cs65.webp',type:'image',cat:'architecture'},
    {name:'城市66',url:'https://raw.giteeusercontent.com/lanzaong/lan/raw/master/icons/cs/cs66.webp',type:'image',cat:'architecture'},
    {name:'城市67',url:'https://raw.giteeusercontent.com/lanzaong/lan/raw/master/icons/cs/cs67.webp',type:'image',cat:'architecture'},
    {name:'城市68',url:'https://raw.giteeusercontent.com/lanzaong/lan/raw/master/icons/cs/cs68.webp',type:'image',cat:'architecture'},
    {name:'城市69',url:'https://raw.giteeusercontent.com/lanzaong/lan/raw/master/icons/cs/cs69.webp',type:'image',cat:'architecture'},
    {name:'城市70',url:'https://raw.giteeusercontent.com/lanzaong/lan/raw/master/icons/cs/cs70.webp',type:'image',cat:'architecture'},
    {name:'城市71',url:'https://raw.giteeusercontent.com/lanzaong/lan/raw/master/icons/cs/cs71.webp',type:'image',cat:'architecture'},
    {name:'城市72',url:'https://raw.giteeusercontent.com/lanzaong/lan/raw/master/icons/cs/cs72.webp',type:'image',cat:'architecture'},
    {name:'城市73',url:'https://raw.giteeusercontent.com/lanzaong/lan/raw/master/icons/cs/cs73.webp',type:'image',cat:'architecture'},
    {name:'城市74',url:'https://raw.giteeusercontent.com/lanzaong/lan/raw/master/icons/cs/cs74.webp',type:'image',cat:'architecture'},
    {name:'城市75',url:'https://raw.giteeusercontent.com/lanzaong/lan/raw/master/icons/cs/cs75.webp',type:'image',cat:'architecture'},
    {name:'城市76',url:'https://raw.giteeusercontent.com/lanzaong/lan/raw/master/icons/cs/cs76.webp',type:'image',cat:'architecture'},
    {name:'城市77',url:'https://raw.giteeusercontent.com/lanzaong/lan/raw/master/icons/cs/cs77.webp',type:'image',cat:'architecture'},
    {name:'城市78',url:'https://raw.giteeusercontent.com/lanzaong/lan/raw/master/icons/cs/cs78.webp',type:'image',cat:'architecture'},
    {name:'城市79',url:'https://raw.giteeusercontent.com/lanzaong/lan/raw/master/icons/cs/cs79.webp',type:'image',cat:'architecture'},
    {name:'城市80',url:'https://raw.giteeusercontent.com/lanzaong/lan/raw/master/icons/cs/cs80.webp',type:'image',cat:'architecture'},
    {name:'城市81',url:'https://raw.giteeusercontent.com/lanzaong/lan/raw/master/icons/cs/cs81.webp',type:'image',cat:'architecture'},
    {name:'城市82',url:'https://raw.giteeusercontent.com/lanzaong/lan/raw/master/icons/cs/cs82.webp',type:'image',cat:'architecture'},
    {name:'城市83',url:'https://raw.giteeusercontent.com/lanzaong/lan/raw/master/icons/cs/cs83.webp',type:'image',cat:'architecture'},
    {name:'城市84',url:'https://raw.giteeusercontent.com/lanzaong/lan/raw/master/icons/cs/cs84.webp',type:'image',cat:'architecture'},
    {name:'城市85',url:'https://raw.giteeusercontent.com/lanzaong/lan/raw/master/icons/cs/cs85.webp',type:'image',cat:'architecture'},
    {name:'城市86',url:'https://raw.giteeusercontent.com/lanzaong/lan/raw/master/icons/cs/cs86.webp',type:'image',cat:'architecture'},
    {name:'城市87',url:'https://raw.giteeusercontent.com/lanzaong/lan/raw/master/icons/cs/cs87.webp',type:'image',cat:'architecture'},
    {name:'城市88',url:'https://raw.giteeusercontent.com/lanzaong/lan/raw/master/icons/cs/cs88.webp',type:'image',cat:'architecture'},
    {name:'城市89',url:'https://raw.giteeusercontent.com/lanzaong/lan/raw/master/icons/cs/cs89.webp',type:'image',cat:'architecture'},
    {name:'城市90',url:'https://raw.giteeusercontent.com/lanzaong/lan/raw/master/icons/cs/cs90.webp',type:'image',cat:'architecture'},
    {name:'城市91',url:'https://raw.giteeusercontent.com/lanzaong/lan/raw/master/icons/cs/cs91.webp',type:'image',cat:'architecture'},
    {name:'城市92',url:'https://raw.giteeusercontent.com/lanzaong/lan/raw/master/icons/cs/cs92.webp',type:'image',cat:'architecture'},
    {name:'城市93',url:'https://raw.giteeusercontent.com/lanzaong/lan/raw/master/icons/cs/cs93.webp',type:'image',cat:'architecture'},
    {name:'城市94',url:'https://raw.giteeusercontent.com/lanzaong/lan/raw/master/icons/cs/cs94.webp',type:'image',cat:'architecture'},
    {name:'城市95',url:'https://raw.giteeusercontent.com/lanzaong/lan/raw/master/icons/cs/cs95.webp',type:'image',cat:'architecture'},
    {name:'城市96',url:'https://raw.giteeusercontent.com/lanzaong/lan/raw/master/icons/cs/cs96.webp',type:'image',cat:'architecture'},
    {name:'城市97',url:'https://raw.giteeusercontent.com/lanzaong/lan/raw/master/icons/cs/cs97.webp',type:'image',cat:'architecture'},
    {name:'城市98',url:'https://raw.giteeusercontent.com/lanzaong/lan/raw/master/icons/cs/cs98.webp',type:'image',cat:'architecture'},
    {name:'城市99',url:'https://raw.giteeusercontent.com/lanzaong/lan/raw/master/icons/cs/cs99.webp',type:'image',cat:'architecture'},
    {name:'城市100',url:'https://raw.giteeusercontent.com/lanzaong/lan/raw/master/icons/cs/cs100.webp',type:'image',cat:'architecture'},
    {name:'城市101',url:'https://raw.giteeusercontent.com/lanzaong/lan/raw/master/icons/cs/cs101.webp',type:'image',cat:'architecture'},
    {name:'城市102',url:'https://raw.giteeusercontent.com/lanzaong/lan/raw/master/icons/cs/cs102.webp',type:'image',cat:'architecture'},
    {name:'城市103',url:'https://raw.giteeusercontent.com/lanzaong/lan/raw/master/icons/cs/cs103.webp',type:'image',cat:'architecture'},
    {name:'城市104',url:'https://raw.giteeusercontent.com/lanzaong/lan/raw/master/icons/cs/cs104.webp',type:'image',cat:'architecture'},
    {name:'城市105',url:'https://raw.giteeusercontent.com/lanzaong/lan/raw/master/icons/cs/cs105.webp',type:'image',cat:'architecture'},
    {name:'城市106',url:'https://raw.giteeusercontent.com/lanzaong/lan/raw/master/icons/cs/cs106.webp',type:'image',cat:'architecture'},
    {name:'城市107',url:'https://raw.giteeusercontent.com/lanzaong/lan/raw/master/icons/cs/cs107.webp',type:'image',cat:'architecture'},
    {name:'城市108',url:'https://raw.giteeusercontent.com/lanzaong/lan/raw/master/icons/cs/cs108.webp',type:'image',cat:'architecture'},
    {name:'城市109',url:'https://raw.giteeusercontent.com/lanzaong/lan/raw/master/icons/cs/cs109.webp',type:'image',cat:'architecture'},
    {name:'城市110',url:'https://raw.giteeusercontent.com/lanzaong/lan/raw/master/icons/cs/cs110.webp',type:'image',cat:'architecture'},
    {name:'城市111',url:'https://raw.giteeusercontent.com/lanzaong/lan/raw/master/icons/cs/cs111.webp',type:'image',cat:'architecture'},
    {name:'城市112',url:'https://raw.giteeusercontent.com/lanzaong/lan/raw/master/icons/cs/cs112.webp',type:'image',cat:'architecture'},
    {name:'城市113',url:'https://raw.giteeusercontent.com/lanzaong/lan/raw/master/icons/cs/cs113.webp',type:'image',cat:'architecture'},
    {name:'城市114',url:'https://raw.giteeusercontent.com/lanzaong/lan/raw/master/icons/cs/cs114.webp',type:'image',cat:'architecture'},
    {name:'城市115',url:'https://raw.giteeusercontent.com/lanzaong/lan/raw/master/icons/cs/cs115.webp',type:'image',cat:'architecture'},
    {name:'城市116',url:'https://raw.giteeusercontent.com/lanzaong/lan/raw/master/icons/cs/cs116.webp',type:'image',cat:'architecture'},
    {name:'城市117',url:'https://raw.giteeusercontent.com/lanzaong/lan/raw/master/icons/cs/cs117.webp',type:'image',cat:'architecture'},
    /* === 汽车 (automobile) === */
    {name:'汽车1',url:'https://raw.giteeusercontent.com/lanzaong/lan/raw/master/icons/chiche/chiche1.webp',type:'image',cat:'automobile'},
    {name:'汽车2',url:'https://raw.giteeusercontent.com/lanzaong/lan/raw/master/icons/chiche/chiche2.webp',type:'image',cat:'automobile'},
    {name:'汽车3',url:'https://raw.giteeusercontent.com/lanzaong/lan/raw/master/icons/chiche/chiche3.webp',type:'image',cat:'automobile'},
    {name:'汽车4',url:'https://raw.giteeusercontent.com/lanzaong/lan/raw/master/icons/chiche/chiche4.webp',type:'image',cat:'automobile'},
    {name:'汽车5',url:'https://raw.giteeusercontent.com/lanzaong/lan/raw/master/icons/chiche/chiche5.webp',type:'image',cat:'automobile'},
    {name:'汽车6',url:'https://raw.giteeusercontent.com/lanzaong/lan/raw/master/icons/chiche/chiche6.webp',type:'image',cat:'automobile'},
    {name:'汽车7',url:'https://raw.giteeusercontent.com/lanzaong/lan/raw/master/icons/chiche/chiche7.webp',type:'image',cat:'automobile'},
    {name:'汽车8',url:'https://raw.giteeusercontent.com/lanzaong/lan/raw/master/icons/chiche/chiche8.webp',type:'image',cat:'automobile'},
    {name:'汽车9',url:'https://raw.giteeusercontent.com/lanzaong/lan/raw/master/icons/chiche/chiche9.webp',type:'image',cat:'automobile'},
    {name:'汽车10',url:'https://raw.giteeusercontent.com/lanzaong/lan/raw/master/icons/chiche/chiche10.webp',type:'image',cat:'automobile'},
    {name:'汽车11',url:'https://raw.giteeusercontent.com/lanzaong/lan/raw/master/icons/chiche/chiche11.webp',type:'image',cat:'automobile'},
    {name:'汽车12',url:'https://raw.giteeusercontent.com/lanzaong/lan/raw/master/icons/chiche/chiche12.webp',type:'image',cat:'automobile'},
    {name:'汽车13',url:'https://raw.giteeusercontent.com/lanzaong/lan/raw/master/icons/chiche/chiche13.webp',type:'image',cat:'automobile'},
    {name:'汽车14',url:'https://raw.giteeusercontent.com/lanzaong/lan/raw/master/icons/chiche/chiche14.webp',type:'image',cat:'automobile'},
    {name:'汽车15',url:'https://raw.giteeusercontent.com/lanzaong/lan/raw/master/icons/chiche/chiche15.webp',type:'image',cat:'automobile'},
    {name:'汽车16',url:'https://raw.giteeusercontent.com/lanzaong/lan/raw/master/icons/chiche/chiche16.webp',type:'image',cat:'automobile'},
    {name:'汽车17',url:'https://raw.giteeusercontent.com/lanzaong/lan/raw/master/icons/chiche/chiche17.webp',type:'image',cat:'automobile'},
    {name:'汽车18',url:'https://raw.giteeusercontent.com/lanzaong/lan/raw/master/icons/chiche/chiche18.webp',type:'image',cat:'automobile'},
    {name:'汽车19',url:'https://raw.giteeusercontent.com/lanzaong/lan/raw/master/icons/chiche/chiche19.webp',type:'image',cat:'automobile'},
    {name:'汽车20',url:'https://raw.giteeusercontent.com/lanzaong/lan/raw/master/icons/chiche/chiche20.webp',type:'image',cat:'automobile'},
    {name:'汽车21',url:'https://raw.giteeusercontent.com/lanzaong/lan/raw/master/icons/chiche/chiche21.webp',type:'image',cat:'automobile'},
    {name:'汽车22',url:'https://raw.giteeusercontent.com/lanzaong/lan/raw/master/icons/chiche/chiche22.webp',type:'image',cat:'automobile'},
    {name:'汽车23',url:'https://raw.giteeusercontent.com/lanzaong/lan/raw/master/icons/chiche/chiche23.webp',type:'image',cat:'automobile'},
    {name:'汽车24',url:'https://raw.giteeusercontent.com/lanzaong/lan/raw/master/icons/chiche/chiche24.webp',type:'image',cat:'automobile'},
    {name:'汽车25',url:'https://raw.giteeusercontent.com/lanzaong/lan/raw/master/icons/chiche/chiche25.webp',type:'image',cat:'automobile'},
    {name:'汽车26',url:'https://raw.giteeusercontent.com/lanzaong/lan/raw/master/icons/chiche/chiche26.webp',type:'image',cat:'automobile'},
    {name:'汽车27',url:'https://raw.giteeusercontent.com/lanzaong/lan/raw/master/icons/chiche/chiche27.webp',type:'image',cat:'automobile'},
    {name:'汽车28',url:'https://raw.giteeusercontent.com/lanzaong/lan/raw/master/icons/chiche/chiche28.webp',type:'image',cat:'automobile'},
    {name:'汽车29',url:'https://raw.giteeusercontent.com/lanzaong/lan/raw/master/icons/chiche/chiche29.webp',type:'image',cat:'automobile'},
    {name:'汽车30',url:'https://raw.giteeusercontent.com/lanzaong/lan/raw/master/icons/chiche/chiche30.webp',type:'image',cat:'automobile'},
    {name:'汽车31',url:'https://raw.giteeusercontent.com/lanzaong/lan/raw/master/icons/chiche/chiche31.webp',type:'image',cat:'automobile'},
    {name:'汽车32',url:'https://raw.giteeusercontent.com/lanzaong/lan/raw/master/icons/chiche/chiche32.webp',type:'image',cat:'automobile'},
    {name:'汽车33',url:'https://raw.giteeusercontent.com/lanzaong/lan/raw/master/icons/chiche/chiche33.webp',type:'image',cat:'automobile'},
    {name:'汽车34',url:'https://raw.giteeusercontent.com/lanzaong/lan/raw/master/icons/chiche/chiche34.webp',type:'image',cat:'automobile'},
    {name:'汽车35',url:'https://raw.giteeusercontent.com/lanzaong/lan/raw/master/icons/chiche/chiche35.webp',type:'image',cat:'automobile'},
    {name:'汽车36',url:'https://raw.giteeusercontent.com/lanzaong/lan/raw/master/icons/chiche/chiche36.webp',type:'image',cat:'automobile'},
    {name:'汽车37',url:'https://raw.giteeusercontent.com/lanzaong/lan/raw/master/icons/chiche/chiche37.webp',type:'image',cat:'automobile'},
    {name:'汽车38',url:'https://raw.giteeusercontent.com/lanzaong/lan/raw/master/icons/chiche/chiche38.webp',type:'image',cat:'automobile'},
    {name:'汽车39',url:'https://raw.giteeusercontent.com/lanzaong/lan/raw/master/icons/chiche/chiche39.webp',type:'image',cat:'automobile'},
    {name:'汽车40',url:'https://raw.giteeusercontent.com/lanzaong/lan/raw/master/icons/chiche/chiche40.webp',type:'image',cat:'automobile'},
    {name:'汽车41',url:'https://raw.giteeusercontent.com/lanzaong/lan/raw/master/icons/chiche/chiche41.webp',type:'image',cat:'automobile'},
    {name:'汽车42',url:'https://raw.giteeusercontent.com/lanzaong/lan/raw/master/icons/chiche/chiche42.webp',type:'image',cat:'automobile'},
    {name:'汽车43',url:'https://raw.giteeusercontent.com/lanzaong/lan/raw/master/icons/chiche/chiche43.webp',type:'image',cat:'automobile'},
    {name:'汽车44',url:'https://raw.giteeusercontent.com/lanzaong/lan/raw/master/icons/chiche/chiche44.webp',type:'image',cat:'automobile'},
    {name:'汽车45',url:'https://raw.giteeusercontent.com/lanzaong/lan/raw/master/icons/chiche/chiche45.webp',type:'image',cat:'automobile'},
    {name:'汽车46',url:'https://raw.giteeusercontent.com/lanzaong/lan/raw/master/icons/chiche/chiche46.webp',type:'image',cat:'automobile'},
    {name:'汽车47',url:'https://raw.giteeusercontent.com/lanzaong/lan/raw/master/icons/chiche/chiche47.webp',type:'image',cat:'automobile'},
    {name:'汽车48',url:'https://raw.giteeusercontent.com/lanzaong/lan/raw/master/icons/chiche/chiche48.webp',type:'image',cat:'automobile'},
    {name:'汽车49',url:'https://raw.giteeusercontent.com/lanzaong/lan/raw/master/icons/chiche/chiche49.webp',type:'image',cat:'automobile'},
    {name:'汽车50',url:'https://raw.giteeusercontent.com/lanzaong/lan/raw/master/icons/chiche/chiche50.webp',type:'image',cat:'automobile'},
    {name:'汽车51',url:'https://raw.giteeusercontent.com/lanzaong/lan/raw/master/icons/chiche/chiche51.webp',type:'image',cat:'automobile'},
    {name:'汽车52',url:'https://raw.giteeusercontent.com/lanzaong/lan/raw/master/icons/chiche/chiche52.webp',type:'image',cat:'automobile'},
    {name:'汽车53',url:'https://raw.giteeusercontent.com/lanzaong/lan/raw/master/icons/chiche/chiche53.webp',type:'image',cat:'automobile'},
    {name:'汽车54',url:'https://raw.giteeusercontent.com/lanzaong/lan/raw/master/icons/chiche/chiche54.webp',type:'image',cat:'automobile'},
    {name:'汽车55',url:'https://raw.giteeusercontent.com/lanzaong/lan/raw/master/icons/chiche/chiche55.webp',type:'image',cat:'automobile'},
    {name:'汽车56',url:'https://raw.giteeusercontent.com/lanzaong/lan/raw/master/icons/chiche/chiche56.webp',type:'image',cat:'automobile'},
    {name:'汽车57',url:'https://raw.giteeusercontent.com/lanzaong/lan/raw/master/icons/chiche/chiche57.webp',type:'image',cat:'automobile'},
    {name:'汽车58',url:'https://raw.giteeusercontent.com/lanzaong/lan/raw/master/icons/chiche/chiche58.webp',type:'image',cat:'automobile'},
    {name:'汽车59',url:'https://raw.giteeusercontent.com/lanzaong/lan/raw/master/icons/chiche/chiche59.webp',type:'image',cat:'automobile'},
    {name:'汽车60',url:'https://raw.giteeusercontent.com/lanzaong/lan/raw/master/icons/chiche/chiche60.webp',type:'image',cat:'automobile'},
    {name:'汽车61',url:'https://raw.giteeusercontent.com/lanzaong/lan/raw/master/icons/chiche/chiche61.webp',type:'image',cat:'automobile'},
    {name:'汽车62',url:'https://raw.giteeusercontent.com/lanzaong/lan/raw/master/icons/chiche/chiche62.webp',type:'image',cat:'automobile'},
    {name:'汽车63',url:'https://raw.giteeusercontent.com/lanzaong/lan/raw/master/icons/chiche/chiche63.webp',type:'image',cat:'automobile'},
    {name:'汽车64',url:'https://raw.giteeusercontent.com/lanzaong/lan/raw/master/icons/chiche/chiche64.webp',type:'image',cat:'automobile'},
    {name:'汽车65',url:'https://raw.giteeusercontent.com/lanzaong/lan/raw/master/icons/chiche/chiche65.webp',type:'image',cat:'automobile'},
    {name:'汽车66',url:'https://raw.giteeusercontent.com/lanzaong/lan/raw/master/icons/chiche/chiche66.webp',type:'image',cat:'automobile'},
    {name:'汽车67',url:'https://raw.giteeusercontent.com/lanzaong/lan/raw/master/icons/chiche/chiche67.webp',type:'image',cat:'automobile'},
    {name:'汽车68',url:'https://raw.giteeusercontent.com/lanzaong/lan/raw/master/icons/chiche/chiche68.webp',type:'image',cat:'automobile'},
    {name:'汽车69',url:'https://raw.giteeusercontent.com/lanzaong/lan/raw/master/icons/chiche/chiche69.webp',type:'image',cat:'automobile'},
    {name:'汽车70',url:'https://raw.giteeusercontent.com/lanzaong/lan/raw/master/icons/chiche/chiche70.webp',type:'image',cat:'automobile'},
    {name:'汽车71',url:'https://raw.giteeusercontent.com/lanzaong/lan/raw/master/icons/chiche/chiche71.webp',type:'image',cat:'automobile'},
    {name:'汽车72',url:'https://raw.giteeusercontent.com/lanzaong/lan/raw/master/icons/chiche/chiche72.webp',type:'image',cat:'automobile'},
    {name:'汽车73',url:'https://raw.giteeusercontent.com/lanzaong/lan/raw/master/icons/chiche/chiche73.webp',type:'image',cat:'automobile'},
    {name:'汽车74',url:'https://raw.giteeusercontent.com/lanzaong/lan/raw/master/icons/chiche/chiche74.webp',type:'image',cat:'automobile'},
    {name:'汽车75',url:'https://raw.giteeusercontent.com/lanzaong/lan/raw/master/icons/chiche/chiche75.webp',type:'image',cat:'automobile'},
    {name:'汽车76',url:'https://raw.giteeusercontent.com/lanzaong/lan/raw/master/icons/chiche/chiche76.webp',type:'image',cat:'automobile'},
    {name:'汽车77',url:'https://raw.giteeusercontent.com/lanzaong/lan/raw/master/icons/chiche/chiche77.webp',type:'image',cat:'automobile'},
    {name:'汽车78',url:'https://raw.giteeusercontent.com/lanzaong/lan/raw/master/icons/chiche/chiche78.webp',type:'image',cat:'automobile'},
    /* === 插画 (illustration) === */
    {name:'插画1',url:'https://raw.giteeusercontent.com/lanzaong/lan/raw/master/icons/chahua/caha1.webp',type:'image',cat:'illustration'},
    {name:'插画2',url:'https://raw.giteeusercontent.com/lanzaong/lan/raw/master/icons/chahua/caha2.webp',type:'image',cat:'illustration'},
    {name:'插画3',url:'https://raw.giteeusercontent.com/lanzaong/lan/raw/master/icons/chahua/caha3.webp',type:'image',cat:'illustration'},
    {name:'插画4',url:'https://raw.giteeusercontent.com/lanzaong/lan/raw/master/icons/chahua/caha4.webp',type:'image',cat:'illustration'},
    {name:'插画5',url:'https://raw.giteeusercontent.com/lanzaong/lan/raw/master/icons/chahua/caha5.webp',type:'image',cat:'illustration'},
    {name:'插画6',url:'https://raw.giteeusercontent.com/lanzaong/lan/raw/master/icons/chahua/caha6.webp',type:'image',cat:'illustration'},
    {name:'插画7',url:'https://raw.giteeusercontent.com/lanzaong/lan/raw/master/icons/chahua/caha7.webp',type:'image',cat:'illustration'},
    {name:'插画8',url:'https://raw.giteeusercontent.com/lanzaong/lan/raw/master/icons/chahua/caha8.webp',type:'image',cat:'illustration'},
    {name:'插画9',url:'https://raw.giteeusercontent.com/lanzaong/lan/raw/master/icons/chahua/caha9.webp',type:'image',cat:'illustration'},
    {name:'插画10',url:'https://raw.giteeusercontent.com/lanzaong/lan/raw/master/icons/chahua/caha10.webp',type:'image',cat:'illustration'},
    /* === 动态壁纸 (video) === */
    {name:'动态壁纸1',url:'https://video.wetab.link/wallpaper-dynamic/v1gtq6jttneh5kcpw2tk1tadhrum.mp4',type:'video'},
    {name:'动态壁纸2',url:'https://video.wetab.link/wallpaper-dynamic/v1gubo58t2lvaxwexqjk8lmb9t9o.mp4',type:'video'},
    {name:'动态壁纸3',url:'https://video.wetab.link/wallpaper-dynamic/v1gubo4rc9kqmj0mbovym7v9zyz7.mp4',type:'video'},
    {name:'动态壁纸4',url:'https://video.wetab.link/wallpaper-dynamic/v1gubo3mujimsr5p1afezwln3fw6.mp4',type:'video'},
    {name:'动态壁纸5',url:'https://video.wetab.link/wallpaper-dynamic/v1gubo82qfh40okq5qukfkk6az66.mp4',type:'video'},
    {name:'动态壁纸6',url:'https://video.wetab.link/wallpaper-dynamic/v1gubo2cnjw92c4cl0bv0zqtcpa5.mp4',type:'video'},
    {name:'动态壁纸7',url:'https://video.wetab.link/wallpaper-dynamic/v1gtq6mprp8d8344xvqcrsmb9od0.mp4',type:'video'},
    {name:'动态壁纸8',url:'https://video.wetab.link/wallpaper-dynamic/v1gubnp8gkghs4kajwwefs7u8a8f.mp4',type:'video'},
    {name:'动态壁纸9',url:'https://video.wetab.link/wallpaper-dynamic/v1gubno14c8plx23zndbddkakuxp.mp4',type:'video'},
    {name:'动态壁纸10',url:'https://video.wetab.link/wallpaper-dynamic/v1gubnmjm1c1t3ovr1iai77htmxm.mp4',type:'video'},
    {name:'动态壁纸11',url:'https://video.wetab.link/wallpaper-dynamic/v1gtq6m4bdm2e4ufo0sudf5scnte.mp4',type:'video'},
    {name:'动态壁纸12',url:'https://video.wetab.link/wallpaper-dynamic/v1gubo7k2g8upphdq4u4ilz5o1az.mp4',type:'video'},
    {name:'动态壁纸13',url:'https://video.wetab.link/wallpaper-dynamic/v1gubnf5slx41eg9np1i6rybbtsv.mp4',type:'video'},
    {name:'动态壁纸14',url:'https://video.wetab.link/wallpaper-dynamic/v1gtq7olsdfrwjik1d9fstwwgywg.mp4',type:'video'},
    {name:'动态壁纸15',url:'https://video.wetab.link/wallpaper-dynamic/v1gubnfnhr6n3af9urtw69eng00t.mp4',type:'video'},
    {name:'动态壁纸16',url:'https://video.wetab.link/wallpaper-dynamic/v1gubnemu07mlzw6lrd7c6zs0r09.mp4',type:'video'},
    {name:'动态壁纸17',url:'https://video.wetab.link/wallpaper-dynamic/v1gtq7muj107uuw68emwy46t6l04.mp4',type:'video'},
    {name:'动态壁纸18',url:'https://video.wetab.link/wallpaper-dynamic/v1gtq7majg0tla2si4d4e6rn1qvx.mp4',type:'video'},
    {name:'动态壁纸19',url:'https://video.wetab.link/wallpaper-dynamic/v1gtq7a826u6p40cc0axwmco4em8.mp4',type:'video'},
    {name:'动态壁纸20',url:'https://video.wetab.link/wallpaper-dynamic/v1gtq77u4cvcki7ncfc2vwkr4at0.mp4',type:'video'},
    {name:'动态壁纸21',url:'https://video.wetab.link/wallpaper-dynamic/v1gtq73fvg1dpuilqsfdgg579rpk.mp4',type:'video'},
    {name:'动态壁纸22',url:'https://video.wetab.link/wallpaper-dynamic/v1gtq7677qcuepuxucvv9v92z06o.mp4',type:'video'},
    {name:'动态壁纸23',url:'https://video.wetab.link/wallpaper-dynamic/v1gtq6trgkb0pkhoebhmnihqfytt.mp4',type:'video'},
    {name:'动态壁纸24',url:'https://video.wetab.link/wallpaper-dynamic/v1gtq6nbhqr8xyqmidc1jkqhjsi0.mp4',type:'video'}
];

/* 壁纸子分类（静态壁纸下的主题分类） */
var defaultBgCategoryList = [
  {id:'nature',name:'自然风景',cover:'https://img2.baidu.com/it/u=4131187706,24986270&fm=253&fmt=auto&app=120&f=JPEG?w=1422&h=800'},
  {id:'architecture',name:'城市建筑',cover:'https://img1.baidu.com/it/u=1843013763,2149939827&fm=253&fmt=auto&app=120&f=JPEG?w=1422&h=800'},
  {id:'automobile',name:'汽车',cover:'https://img2.baidu.com/it/u=2444527320,3528281971&fm=253&fmt=auto&app=138&f=JPEG?w=889&h=500'},
  {id:'illustration',name:'插画',cover:'https://img2.baidu.com/it/u=921425687,616415413&fm=253&fmt=auto&app=138&f=JPEG?w=889&h=500'}
];

var defaultHotList=[
  {text:'AI人工智能最新进展'},{text:'今日热搜排行榜'},{text:'天气预报实时查询'},
  {text:'热门电影推荐'},{text:'在线工具大全'},{text:'GitHub开源项目'},
  {text:'科技数码资讯'},{text:'生活小妙招'}
];
